services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gh4rris/loan_app
    container_name: app
    depends_on:
      - mlflow
    environment:
      MLFLOW_TRACKING_URI: "http://mlflow_server:5000"
    ports:
      - "8000:8000"
    restart: unless-stopped

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    image: gh4rris/loan_mlflow
    container_name: mlflow_server
    ports:
      - "5000:5000"
    restart: unless-stopped
