services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: loan_approval:latest
    container_name: loan_approval
    depends_on:
      - mlflow
    environment:
      MLFLOW_TRACKING_URI: "http://mlflow:5000"
    ports:
      - "8000:8000"
    restart: unless-stopped

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    image: mlflow-server:latest
    container_name: mlflow-server
    ports:
      - "5000:5000"
    restart: unless-stopped
